### ISSUE TITLE
Can't seem to set breakpoints

### ISSUE THREAD

**Issue by Speak2Erase** [ruby/vscode-rdbg#50]
I can't seem to set breakpoints and the debugger will never pause.
launch.json:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "rdbg",
            "name": "Debug current file",
            "request": "launch",
            "script": "${file}",
            "askParameters": false,
            "debugPort": "12345",
            "waitLaunchTime": 3500,
        },
        {
            "type": "rdbg",
            "name": "Debug with rdbg",
            "request": "launch",
            "script": "${workspaceFolder}/test/embed_test.rb",
            "args": [],
            "askParameters": false,
            "debugPort": "12345",
            "waitLaunchTime": 3500,
            "useBundler": false
        },
    ]
}
```

**Comment by ko1** [comment]
could you show me repro steps?

**Comment by Speak2Erase** [comment]
Oh, I'm so sorry, I never noticed this comment.
There's not really any repro steps, all I'm doing is launching rdbg from vscode, and pointing it to a specific script to run.

**Comment by ko1** [comment]
Same on the small script like:

```
a = 1
b = 2
p a + b # breakpoint here
```

?

**Comment by Speak2Erase** [comment]
Yep

**Comment by ko1** [comment]
Thank you I can reproduce with TCP/IP connection.

**Comment by aaronpropst** [comment]
Any movement or progress on this?  I'm seeing something similar.  `binding.break` at least got my going.. but i sure would appreciate being able to use vscode breakpoints again

**Comment by DaveSanders** [comment]
Its strange, because I know that I've had it working recently with rdbg and this extension, but I don't understand why it stopped working.  Not sure if a gem changed, the extension changed, vsc changed, or what.

I can still cause a breakpoint to hit if I use the `debugger` statement, but I'd like to be able to more arbitrarily set breakpoints.  (Which is especially annoying if I need to set another breakpoint while I'm in the middle of debugging.)

I'm also interested if there's any feedback on this issue, or if there are steps we can take to restore it. Or if its a true issue that needs fixed in the extension?  I.e. is this happening for everyone, or just some setups?

**Comment by ko1** [comment]
Sorry I forget it... it can be a debug.gem's problem.

**Comment by vitobotta** [comment]
Hi, I am experimenting with this extension together with rdbg and came across this issue. Last update was in Feb 2023, is this supposed to be working fine now? Thanks!

**Comment by wildmaples** [comment]
I don't think it is working fine now - I am still seeing this issue with this extension and the latest debug 1.9.1. 

However, similar to @DaveSanders 's experience, breakpoints start working again once I restarted my laptop.

**Comment by drewlustro** [comment]
Also seeing this. Clearing VSCode cache did nothing.
